server:
  port: 8082

spring:
  application:
    name: plataforma
  datasource:
    url: jdbc:mysql://localhost:3306/plataforma_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always